name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download Font File
        run: |
          echo "Downloading font file..."
          # Use -s to silence progress, -S to show errors, -L to follow redirects
          curl -s -S -L -o helvetiker_regular.typeface.json https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/fonts/helvetiker_regular.typeface.json
          
          # Verify the file starts with a JSON opening brace
          if ! grep -q "^{" helvetiker_regular.typeface.json; then
            echo "Error: Downloaded file is not valid JSON"
            cat helvetiker_regular.typeface.json | head -n 5
            exit 1
          fi
          
          echo "Font file downloaded successfully"
          file_size=$(stat -c%s helvetiker_regular.typeface.json)
          echo "Font file size: $file_size bytes"
          
          if [ $file_size -lt 1000 ]; then
            echo "Font file is too small, likely an error occurred"
            exit 1
          fi
          
          echo "Font file validation passed"
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 